### ISSUE TITLE
NullPointerException on command /am toggle

### ISSUE THREAD

**Issue by nicku1** [montlikadani/AutoMessager#5]
If you won't add any argument on command /am toggle it will throw NullPointerException. Here is error log ;)

[20:36:58] [Server thread/WARN]: java.lang.NullPointerException
[20:36:58] [Server thread/WARN]: 	at hu.montlikadani.AutoMessager.Commands.onCommand(Commands.java:97)
[20:36:58] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[20:36:58] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[20:36:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[20:36:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[20:36:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[20:36:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[20:36:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[20:36:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[20:36:58] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:36:58] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:36:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[20:36:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[20:36:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[20:36:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[20:36:58] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[20:36:58] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by montlikadani** [comment]
Ooops... Message error.
**Thank you!**

**Comment by montlikadani** [comment]
**_This bug has been fixed in this version:_** https://www.spigotmc.org/resources/automessager.43875/update?update=232831
